services:
  - type: web
    name: deep-research-api
    runtime: docker
    rootDir: Deep_Research
    plan: free
    region: singapore # Optional: Choose a region close to you or your users
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
